### ISSUE TITLE
头条小程序端“滑动逐渐显示背景”Bug以及解决办法

### ISSUE THREAD

**Issue by jsonwu5** [Asuancaiyu/uniapp#1]
在头条端 滑动逐渐显示背景 的示例不生效，背景色没有被正常设置。
经过一番排查，头条端必须在页面上定义 onPageScroll(e){} 方法，然后在组件里才能监听到页面滚动。

希望可以在文档上备注一下，以免更多人踩坑。

另外头条端设置导航栏颜色控制台会提示 头条小程序 暂不支持setNavigationBarColor，是uni还没更新对头条端的支持，但是头条端已经更新了API，可以设置导航栏颜色，需要条件编译。相关文档：[设置导航栏颜色](https://microapp.bytedance.com/dev/cn/mini-app/develop/api/interface/navigation-bar/setnavigationbarcolor)

**Comment by Asuancaiyu** [comment]
非常感谢你的反馈和提供的解决方法！我已修改了该插件。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jason"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月21日(星期六) 下午3:47
收件人:&nbsp;"Asuancaiyu/uniapp"<uniapp@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Asuancaiyu/uniapp] 头条小程序端“滑动逐渐显示背景”Bug以及解决办法 (#1)




在头条端 滑动逐渐显示背景 的示例不生效，背景色没有被正常设置。
 经过一番排查，头条端必须在页面上定义 onPageScroll(e){} 方法，然后在组件里才能监听到页面滚动。
 
希望可以在文档上备注一下，以免更多人踩坑。
 
另外头条端设置导航栏颜色控制台会提示 头条小程序 暂不支持setNavigationBarColor，是uni还没更新对头条端的支持，但是头条端已经更新了API，可以设置导航栏颜色，需要条件编译。相关文档：设置导航栏颜色
